# Generated by Django 4.1 on 2022-09-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mainImage',
            field=models.ImageField(default='Null', null=True, upload_to=''),
        ),
    ]
