# Generated by Django 4.1 on 2022-09-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_post_mainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mainImage',
            field=models.ImageField(default='Null', null=True, upload_to='src/blog_post/static/main_post'),
        ),
    ]
