# Generated by Django 4.1 on 2022-09-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0003_alter_post_mainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mainImage',
            field=models.ImageField(default='Null', null=True, upload_to='static/main_post'),
        ),
    ]
